create database LP;
use LP ;

-- accounts-- 
-- data_dictionary
-- products
-- sales_pipeline
-- sales_team-- 
show tables from LP;
select count(*) from accounts;
select count(*) from data_dictionary ;
select count(*) from sales_teams;
select count(*) from products ;
select count(*) from sales_pipeline ;

select * from sales_pipeline ;
select * from products ;
select * from sales_teams;
select * from data_dictionary ;
select * from accounts; 


-- Data Cleaning And Manipulating 
select *, row_number() over(partition by account,sector, year_established) as rn from accounts;
select *, row_number() over(partition by sales_agent,manager,regional_office) as rn from sales_teams;
select *, row_number() over(partition by product,series,sales_price) as rn from products ;

SELECT opportunity_id,COUNT(*)
FROM sales_pipeline
GROUP BY opportunity_id
HAVING COUNT(*) > 1;

#Null Value Check-- 

SELECT *
FROM accounts
WHERE account IS NULL
   OR sector IS NULL
   OR year_established IS NULL;


SELECT 
    SUM(CASE WHEN account IS NULL THEN 1 ELSE 0 END) AS account_nulls,
    SUM(CASE WHEN sector IS NULL THEN 1 ELSE 0 END) AS sector_nulls,
    SUM(CASE WHEN year_established IS NULL THEN 1 ELSE 0 END) AS year_established_nulls,
    SUM(CASE WHEN revenue IS NULL THEN 1 ELSE 0 END) AS revenue_nulls,
    SUM(CASE WHEN employees IS NULL THEN 1 ELSE 0 END) AS employees_nulls,
    SUM(CASE WHEN office_location IS NULL THEN 1 ELSE 0 END) AS office_location_nulls,
    SUM(CASE WHEN subsidiary_of IS NULL THEN 1 ELSE 0 END) AS subsidiary_of_nulls
FROM accounts;

SELECT 
    SUM(CASE WHEN product IS NULL THEN 1 ELSE 0 END) AS product_nulls,
    SUM(CASE WHEN series IS NULL THEN 1 ELSE 0 END) AS series_nulls,
    SUM(CASE WHEN sales_price IS NULL THEN 1 ELSE 0 END) AS sales_price_nulls
FROM products;



SELECT 
    SUM(CASE WHEN sales_agent IS NULL THEN 1 ELSE 0 END) AS agent_nulls,
    SUM(CASE WHEN manager IS NULL THEN 1 ELSE 0 END) AS manager_nulls,
    SUM(CASE WHEN regional_office IS NULL THEN 1 ELSE 0 END) AS office_nulls
FROM sales_teams;

SELECT 
    SUM(CASE WHEN opportunity_id IS NULL THEN 1 ELSE 0 END) AS opp_id_nulls,
    SUM(CASE WHEN sales_agent IS NULL THEN 1 ELSE 0 END) AS agent_nulls,
    SUM(CASE WHEN product IS NULL THEN 1 ELSE 0 END) AS product_nulls,
    SUM(CASE WHEN account IS NULL THEN 1 ELSE 0 END) AS account_nulls,
    SUM(CASE WHEN deal_stage IS NULL THEN 1 ELSE 0 END) AS stage_nulls,
    SUM(CASE WHEN engage_date IS NULL THEN 1 ELSE 0 END) AS engage_date_nulls,
    SUM(CASE WHEN close_date IS NULL THEN 1 ELSE 0 END) AS close_date_nulls,
    SUM(CASE WHEN close_value IS NULL THEN 1 ELSE 0 END) AS close_value_nulls
FROM sales_pipeline;




SET SQL_SAFE_UPDATES = 0;

UPDATE accounts
SET subsidiary_of = 'Independent'
WHERE subsidiary_of = '';

SET SQL_SAFE_UPDATES = 1;


SELECT 
    SUM(opportunity_id = '') AS opp_id_blanks,
    SUM(sales_agent = '') AS agent_blanks,
    SUM(product = '') AS product_blanks,
    SUM(account = '') AS account_blanks,
    SUM(deal_stage = '') AS stage_blanks,
    SUM(engage_date = '') AS engage_date_blanks,
    SUM(close_date = '') AS close_date_blanks,
    SUM(close_value = '') AS close_value_blanks
FROM sales_pipeline;

SELECT 
    SUM(sales_agent = '') AS agent_blanks,
    SUM(manager = '') AS manager_blanks,
    SUM(regional_office = '') AS office_blanks
FROM sales_teams;



SELECT 
    SUM(product = '') AS product_blanks,
    SUM(series = '') AS series_blanks,
    SUM(sales_price = '') AS sales_price_blanks
FROM products;


SELECT 
    SUM(account = '') AS account_blanks,
    SUM(sector = '') AS sector_blanks,
    SUM(year_established = '') AS year_established_blanks,
    SUM(revenue = '') AS revenue_blanks,
    SUM(employees = '') AS employees_blanks,
    SUM(office_location = '') AS office_location_blanks,
    SUM(subsidiary_of = '') AS subsidiary_of_blanks
FROM accounts;


UPDATE sales_pipeline
SET product = 'GTX Pro'
WHERE product = 'GTXPro';




-- Data Modeling

CREATE VIEW crm_sales_model AS
SELECT
    sp.opportunity_id,
    sp.deal_stage,
    sp.engage_date,
    sp.close_date,
    sp.close_value,

    a.account,
    a.sector,
    a.revenue AS company_revenue,
    a.employees,
    a.office_location,

    p.product,
    p.series,
    p.sales_price,

    st.sales_agent,
    st.manager,
    st.regional_office

FROM sales_pipeline sp

LEFT JOIN accounts a
ON sp.account = a.account

LEFT JOIN products p
ON sp.product = p.product

LEFT JOIN sales_teams st
ON sp.sales_agent = st.sales_agent;


SELECT *
FROM crm_sales_model
;




-- Analytical Questions


-- Q1: How many days did each deal take to complete?
SELECT opportunity_id, account, DATEDIFF(close_date, engage_date) AS Complete_Deal_Time 
FROM crm_sales_model;


-- Q1: What is the total revenue generated by each account(Company)?
select `account`,sum(company_revenue)as Total_Revenue  from crm_sales_model group by `account`;

-- Q2: How many deals were lost for each product?
select `product`, `deal_stage`,count(*) as Deal_count from  crm_sales_model where deal_stage = 'Lost' group by `product` ,`deal_stage`;

-- Q3: How many deals were won for each product?
select `product`, `deal_stage`,count(*) as Deal_count from  crm_sales_model where deal_stage = 'Won' group by `product` ,`deal_stage`;


SELECT *
FROM crm_sales_model
;

-- Q5: What is the maximum revenue deal for each account and sector?
select account as company_name, sector, max(company_revenue) as sector_revenue
from crm_sales_model
group by company_name , sector;

-- Q6: On average, how many days did it take to win deals?

 with Diff as (
    select deal_stage,
           datediff(close_date, engage_date) as Complete_Deal_Time
    from crm_sales_model
)
select deal_stage, avg(Complete_Deal_Time) as Avg_Won_Time
from Diff
where deal_stage = 'Won'
group by deal_stage;
  
  -- Q7: What is the win percentage for each account and office location?
  
  select account as company_name ,office_location ,count(*) as total_deals, sum(case when deal_stage= 'Won' then 1 else 0 end)
  as Won_Deals, round(sum(case when deal_stage= 'Won' then 1 else 0 end)*100.0 /count(*),2)as  Win_Percentage
  from crm_sales_model group by company_name ,office_location ;
  
  -- Q8: What are the total sales and sales rank for each product?
SELECT product,
       SUM(sales_price) AS Total_Sales,
       RANK() OVER (ORDER BY SUM(sales_price) DESC) AS Sales_Rank
FROM crm_sales_model
GROUP BY product;
  
-- Q9: What are the monthly sales for each product in 2017?
select product,
       monthname(close_date) as Month_Name,
       sum(sales_price) as Monthly_Sales
from crm_sales_model
where year(close_date) = 2017
group by product, month(close_date), monthname(close_date)
order by product, month(close_date) ;

  -- Q10: How many deals were won by each sales agent?
 select sales_agent , count(*) as agent_Won_deal from crm_sales_model where deal_stage='Won' group by sales_agent;


-- Q11: For each sales agent, what is the average, fastest, and slowest closing time, and how many deals did they win?

  with Diff as (
    select sales_agent,
           deal_stage,
           datediff(close_date, engage_date) as Complete_Deal_Time
    from crm_sales_model
    where deal_stage = 'Won'
)
select sales_agent,
       avg(Complete_Deal_Time) as Avg_Closing_Days,
       min(Complete_Deal_Time) as Fastest_Deal,
       max(Complete_Deal_Time) as Slowest_Deal,
       count(*) as Total_Won_Deals
from Diff
group by sales_agent
order by Avg_Closing_Days asc ;

  -- Q12: Which top 5 managers generated the highest revenue from won deals?
  select manager ,sum(close_value) as deal_revenue from crm_sales_model where deal_stage = 'Won'
  group by manager order by deal_revenue limit 5;
  
  
-- Q13: What is the monthly revenue trend for won deals?

  SELECT 
    YEAR(close_date) yr,
    MONTH(close_date) mn,
    SUM(close_value) revenue
FROM crm_sales_model
WHERE deal_stage='Won'
GROUP BY YEAR(close_date),MONTH(close_date)
ORDER BY yr,mn desc;
  
  
  
  SELECT *
FROM crm_sales_model
;

 -- Q14: For each industry sector, what is the total number of won/lost deals and the average time taken to close them?

  
SELECT 
    sector,
    SUM(CASE WHEN deal_stage = 'Lost' THEN 1 ELSE 0 END) AS Lost_Deals,
    SUM(CASE WHEN deal_stage = 'Won' THEN 1 ELSE 0 END) AS Won_Deals,
    COUNT(*) AS Total_Deals,
    ROUND(AVG(CASE WHEN deal_stage = 'Lost' THEN DATEDIFF(close_date, engage_date) END),2) AS Avg_Lost_Time,
    ROUND(AVG(CASE WHEN deal_stage = 'Won' THEN DATEDIFF(close_date, engage_date) END),2) AS Avg_Won_Time
FROM crm_sales_model
WHERE deal_stage IN ('Lost','Won')
GROUP BY sector;

-- Q15: What is the total revenue breakdown by regional office and product, ordered from highest to lowest?

SELECT regional_office, product,
       SUM(close_value) AS total_revenue 
FROM crm_sales_model
GROUP BY regional_office,product
ORDER BY total_revenue DESC;









